// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import IconsController from "./icons_controller"
application.register("icons", IconsController)

import ClipboardController from "./clipboard_controller"
application.register("clipboard", ClipboardController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import ChipSelectController from "./chip_select_controller"
application.register("chip-select", ChipSelectController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)
